### ISSUE TITLE
Fix soon

### ISSUE THREAD

**Issue by Praxthisnovcht** [Praxthisnovcht/CustomChat#24]
Support EconomyJOB in progress 50%
Support PlayerStats stop
Fix MassiveEconomy not Load Fixed
Fix KillChat Load and Not load Fixed
add options CustomJoin Fixed 

		$format = str_replace ( "{Kills}", KillChat::getInstance()->getKills($player->getName()), $format); 
will not charge

		$format = str_replace ( "{Money}", MassiveEconomyAPI::getInstance()->getMoney($player->getName()), $format); 
It seems to work fine but when MassiveEconomy is not loaded, He wants to charge.

/*Economy$Job API*/
        if($this->economyjob && isset($this->economyjob->getPlayers()[$player->getName()])
                    $job = $this->economyjob->player->get($sender->getName());
                    $format = str_replace("{JOB}",$job, $format);
        }else{
            $nojob = $this->pgin->getConfig()->get("if-player-has-no-job");
            $format = str_replace("{JOB}",$nojob, $format);
        }
        /*Economy$Job API END*/

**Comment by Praxthisnovcht** [comment]
[x] Support MassiveEconomy

**Comment by Flavius12** [comment]
I think we should rewrite part of code because I noticed some bugs

**Comment by Flavius12** [comment]
If Saturday I have time I'll fix some bugs rewriting the code

**Comment by Flavius12** [comment]
If Saturday I have time I'll fix some bugs rewriting the code

**Comment by Praxthisnovcht** [comment]
there there's a small error code when / defprefix.
 nothing tragic xD

 glad to see you like CustomChat xD

**Comment by Praxthisnovcht** [comment]
Support KillChat ready to send !

**Comment by Praxthisnovcht** [comment]
Support KillChat Version 1.3.2 :+1:
